version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    groups:
      opentelemetry:
        patterns:
          - opentelemetry*
          - "@opentelemetry/*"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
